### ISSUE TITLE
[AccountEligibility] API interface for automatic vote checking?

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#100]
Could it be possible to have some sort of "bot output" so bots such as AlchBot from @alchimista could do the verification themselves without human intervention? My idea is that maybe AlchBot could query the AccountEligibility data and be displayed in a bot-readable format. Then AlchBot tags the votes as eligible or not. Any chances? Regards.

**Comment by Pathoschild** [comment]
See #40.
