### ISSUE TITLE
[stalktoy] not showing either block

### ISSUE THREAD

**Issue by Jeff-Gdot** [Pathoschild/Wikimedia-contrib#102]
https://tools.wmflabs.org/meta/stalktoy/Xx+BlackSheep+xX does not show either of the blocks at https://commons.wikimedia.org/w/index.php?title=Special:Log&page=User%3AXx_BlackSheep_xX&type=block

**Comment by Pathoschild** [comment]
The tool does show the block now, so it was probably due to a temporary database issue (e.g. replication lag). Thanks for reporting it!
