### ISSUE TITLE
All of your tools broken

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#103]
`Fatal error: Invalid serialization data for DateTime object in /mnt/nfs/labstore-secondary-tools-project/meta/git/wikimedia-contrib/tool-labs/backend/modules/Cacher.php on line 153`

This message is appearing on all of your tools since yesterday. For example: https://tools.wmflabs.org/meta/userpages/MarcoAurelio

Any idea what's going on?

Thank you!

**Comment by Pathoschild** [comment]
Fixed. The errors were caused by a cache file containing invalid data somehow; I cleared the cache and everything should be fine now. Thanks for reporting it!
