### ISSUE TITLE
[AccountEligibility] Possible miscounting -- POTY 2017 of User:Marcel64121

### ISSUE THREAD

**Issue by zhuyifei1999** [Pathoschild/Wikimedia-contrib#105]
https://tools.wmflabs.org/meta/accounteligibility/47/Marcel64121 claims that this user has 75 edits before 2018 on frwiki, but I only see [73](https://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:Contributions/Marcel64121&dir=prev&limit=75&target=Marcel64121&uselang=en). In events.php we [did not](https://github.com/Pathoschild/Wikimedia-contrib/blob/52be4d6e1f3089c95e1ed85d518ede501eeff4d6/tool-labs/accounteligibility/events.php#L30) specify `EditCountRule::COUNT_DELETED` so I'm assuming it counts only live non-deleted edits, like according to our [eligibility rules](https://commons.wikimedia.org/wiki/Commons:Picture_of_the_Year/2017/Rules#Voter_eligibility). So where are the two 'ghost' edits?

**Comment by Pathoschild** [comment]
@zhuyifei1999 I found these four revisions for that user:

```
[frwiki_p]> SELECT rev_timestamp, page_title, rev_comment FROM revision_userindex LEFT JOIN page ON rev_page = page_id WHERE rev_user = 2130537 AND rev_timestamp < 20180100000000 ORDER BY rev_timestamp DESC;
+----------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| rev_timestamp  | page_title         | rev_comment                                                                                                                                              |
+----------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| ...            | ...                | ...                                                                                                                                                      |
| 20160627144145 | NULL               | Marcel64121 a déplacé la page [[Discussion:Aquitaine-Limousin-Poitou-Charentes]] vers [[Discussion:Nouvelle-Aquitaine]] : La région a changé de nom      |
| 20160627144145 | Nouvelle-Aquitaine | Marcel64121 a déplacé la page [[Discussion:Aquitaine-Limousin-Poitou-Charentes]] vers [[Discussion:Nouvelle-Aquitaine]] : La région a changé de nom      |
| 20160627144144 | NULL               | Marcel64121 a déplacé la page [[Aquitaine-Limousin-Poitou-Charentes]] vers [[Nouvelle-Aquitaine]] par-dessus une redirection : La région a changé de nom |
| 20160627144142 | Nouvelle-Aquitaine | Marcel64121 a déplacé la page [[Aquitaine-Limousin-Poitou-Charentes]] vers [[Nouvelle-Aquitaine]] par-dessus une redirection : La région a changé de nom |
+----------------+--------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
75 rows in set (0.01 sec)
```

The [contributions page](https://fr.wikipedia.org/wiki/Sp%C3%A9cial:Contributions/Marcel64121?dir=prev&limit=75&target=Marcel64121&uselang=en) does show those page moves, but there's two revisions for each move in the database. It looks like ignoring revisions linked to an invalid page ID should fix it, but I'd want to look into why that happens first.

**Comment by zhuyifei1999** [comment]
I think these revisions belong to a page that somehow doesn't exist, and LEFT JOIN NULLs the column.
```
MariaDB [frwiki_p]> SELECT rev_page, page_id FROM revision_userindex LEFT JOIN page ON rev_page = page_id WHERE rev_user = 2130537 AND rev_timestamp < 20180100000000 AND page_title IS NULL ORDER BY rev_timestamp DESC;
+----------+---------+
| rev_page | page_id |
+----------+---------+
| 10111191 |    NULL |
| 10111190 |    NULL |
+----------+---------+
2 rows in set (0.04 sec)

MariaDB [frwiki_p]> SELECT * FROM page WHERE page_id IN (10111191, 10111190);
Empty set (0.00 sec)
```
But I don't understand how a row in the page table can just go 'missing'. The page table isn't one that has secret data and redacts rows.

**Comment by zhuyifei1999** [comment]
Something interesting is that [the pages are moved over redirect](https://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:Journal&page=Aquitaine-Limousin-Poitou-Charentes).

**Comment by Pathoschild** [comment]
This might be a bug in MediaWiki; I'm not sure if storing revisions for an invalid page ID when pages are moved over a redirect is intentional.
