### ISSUE TITLE
Fatal error: Invalid serialization data for DateTime object

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#108]
Hello,

Visiting the [stewardry tool](https://tools.wmflabs.org/meta/stewardry/eswikibooks?bot=1) for eswikibooks I got the following error:

```
Fatal error: Invalid serialization data for DateTime object in /mnt/nfs/labstore-secondary-tools-project/meta/git/wikimedia-contrib/tool-labs/backend/modules/Cacher.php on line 153
```

I guess some caching issues?

Please also note that `wikimediafoundation.org` was moved to `foundation.wikimedia.org` (the first is now a WordPress-like site) just in case that needs to be adjusted elsewhere.

Thank you.

Best regards.

**Comment by Pathoschild** [comment]
@MarcoAurelioWM Thanks for reporting it! I deleted the cache to fix the immediate error, so all the tools are back online.

This is caused by a bug in PHP 5 which is practically impossible to handle, since `unserialize` throws a fatal exception in that case. The longer-term fix will be migrating to the [PHP 7.2 beta webservice](https://lists.wikimedia.org/pipermail/cloud/2018-August/000367.html). I'll need to review the migration notes for PHP [7.0](https://secure.php.net/manual/en/migration70.php), [7.1](https://secure.php.net/manual/en/migration71.php), and [7.2](https://secure.php.net/manual/en/migration72.php) first to update the tool code.

**Comment by Pathoschild** [comment]
For reference, here's how to test PHP 7.2 compatibility on Tool Labs. This should catch most issues before you switch on PHP 7 mode.

1. Launch a PHP 7.2 shell in an SSH session:
   ```
   webservice --backend=kubernetes php7.2 shell
   ```
2. Install [PHPStan](https://github.com/phpstan/phpstan) outside the folder you'll be analysing:
   ```
   composer require --dev phpstan/phpstan
   ```
3. If needed, create an `autoload.php` file which maps classes to files for PHPStan. I wrote my tools before the PSR autoloading standards, so mine is a bit messy:
   ```php
   spl_autoload_register(function ($className) {
       // strip namespace
       $parts = explode('\\', $className);
       $className = array_pop($parts);
   
       // search paths
       $root = "/data/project/pathoschild-contrib/git/wikimedia-contrib/tool-labs/";
       $paths = [
           "$root/accounteligibility/framework/$className.php",
           "$root/accounteligibility/framework/constants/$className.php",
           "$root/accounteligibility/framework/models/$className.php",
           "$root/accounteligibility/framework/rules/$className.php",
           "$root/backend/models/$className.php",
           "$root/backend/modules/$className.php",
           "$root/backend/modules/external/$className.php",
           "$root/catanalysis/framework/$className.php",
           "$root/catanalysis/framework/models/$className.php",
           "$root/crossactivity/framework/$className.php",
           "$root/globalgroups/framework/$className.php",
           "$root/gusersearch/framework/$className.php",
           "$root/iso639db/framework/$className.php",
           "$root/stalktoy/framework/$className.php",
           "$root/stalktoy/framework/models/$className.php",
           "$root/stewardry/framework/$className.php"
       ];
   
       foreach ($paths as $path) {
           if (file_exists($path)) {
               require($path);
               break;
           }
       }
   });
   ````

4. Run PHPStan on your code files and specify the autoload file. For example:
   ```
   vendor/bin/phpstan analyse tool-labs --autoload-file=/data/project/pathoschild-contrib/git/wikimedia-contrib/autoload.php
   ```
5. If it reports any errors, fix them and repeat step 4.
6. Repeat step 4&ndash;5 with [higher rule levels](https://github.com/phpstan/phpstan#rule-levels).

**Comment by Pathoschild** [comment]
@MarcoAurelioWM The tools are now running PHP 7, which should prevent the error you reported from happening in the future. Let me know if you notice any further issues. Thanks again for reporting it!
