### ISSUE TITLE
Update foundationwiki links to foundation.wikimedia.org

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#109]
https://github.com/Pathoschild/Wikimedia-contrib/blob/52be4d6e1f3089c95e1ed85d518ede501eeff4d6/tool-labs/accounteligibility/events.php#L50

Patch shortly follows.

**Comment by MarcoAurelioWM** [comment]
Has now patch for review. PTAL.

**Comment by Pathoschild** [comment]
Merged and deployed. Thanks!
