### ISSUE TITLE
[MagicRedirect] shnwiki not recognized

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#116]
While trying to handle [this request](https://meta.wikimedia.org/w/index.php?oldid=18662545#Ninjastrikers@shnwiki) the magic redirect tool does not seem to recognize the shnwiki database:

* Request URL: https://tools.wmflabs.org/meta/magicredirect/?url=//meta.wikimedia.org/wiki/Special:UserRights/Ninjastrikers@{wiki.name}?user-reason=%5B%5BSpecial:Permalink/18662545%5D%5D&wiki=shn.wikipedia&redirect=1

* Error message: Could not find a wiki with a domain or database name like 'shn.wikipedia'.

It's one of the newest wikis so maybe the tools needs some sort of cache refreshing in Toolforge?

Best regards.

**Comment by Pathoschild** [comment]
That wiki isn't in the Toolforge database yet:
```
MariaDB [metawiki_p]> SELECT * FROM meta_p.wiki WHERE dbname = 'shnwiki';
Empty set (0.01 sec)
```
Based on [this comment](https://phabricator.wikimedia.org/T206777#4781677), that's expected since the wiki creation is still in progress. Once it's added, the tools' cache will update automatically within a day (and I can refresh it manually sooner).

**Comment by MarcoAurelioWM** [comment]
Looks like it's already there per
https://phabricator.wikimedia.org/T206916#4781989 ?

**Comment by Pathoschild** [comment]
It doesn't seem to be there yet:
```sql
MariaDB [metawiki_p]> SELECT * FROM meta_p.wiki WHERE dbname = 'shnwiki' OR url = 'https://shn.wikipedia.org';
Empty set (0.00 sec)
```

**Comment by MarcoAurelioWM** [comment]
I could `sql shnwiki` myself on Labs but running the query above indeed
does not return any results, as if the wiki were not known to the
meta_p.wiki table. Weird. I've left a note in the Task.

>

**Comment by Pathoschild** [comment]
It was added a few minutes ago and I cleared the cache, so the link should work now. Thanks for reporting it!
