### ISSUE TITLE
Tools not loading

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#121]
Hello. Since several hours I am unable to access any of your tools. The page loads endesly but never returns anything. Is there anything that can be done to bring the tools back up? Thank you.

**Comment by Pathoschild** [comment]
Are they still not loading for you? I just checked a few sample tools and they're working fine for me.

**Comment by MarcoAurelioWM** [comment]
Hello. They ain't loading for me yet. I'll try to change networks and see
if it is a problem on my end or if there's a Toolforge problem for my
region.

>

**Comment by MarcoAurelioWM** [comment]
I've tested again. The page keeps loading and loading but nothing happens afterwards. Sorry :-(

**Comment by Pathoschild** [comment]
Can you link to a sample URL that never finishes loading?

**Comment by gtirloni** [comment]
I've tried the following URLs and they work for me:

* https://tools.wmflabs.org/meta/accounteligibility/
* https://tools.wmflabs.org/meta

So it was either fixed, temporary or something on @MarcoAurelioWM end.

@MarcoAurelioWM are you still seeing this issue?

**Comment by MarcoAurelioWM** [comment]
They all now load instantly for me. Not sure what it was.

**Comment by gtirloni** [comment]
Distributed systems :)

Toolforge is a shared platform and we are always available to look into things if they're not working. Thanks for reporting it.
