### ISSUE TITLE
[stewardry] enwiki queries don't work

### ISSUE THREAD

**Issue by RhinosF1** [Pathoschild/Wikimedia-contrib#124]
The sysop query fails as 'ysop statistics are disabled for en.wikipedia.org because the result set is too large to process.' and CU fails as 'Fatal error: Uncaught Error: Unsupported operand types in /data/project/meta/git/wikimedia-contrib/tool-labs/stewardry/index.php:65 Stack trace: #0 {main} thrown in /data/project/meta/git/wikimedia-contrib/tool-labs/stewardry/index.php on line 65' 

Not tried any other groups

**Comment by Pathoschild** [comment]
Unfortunately the tool doesn't work for sysops on enwiki, due to the sheer amount of date it would need to sift through. I fixed the error when checking another group though.

**Comment by RhinosF1** [comment]
Was there another tool that found enwiki admins? Could you advise of its name?

**Comment by Pathoschild** [comment]
Not that I know of. Stewardry is meant to check if a wiki has active sysops/etc, which isn't an issue on enwiki. For one-time or occasional results, you could run a custom query through [Quarry](https://quarry.wmflabs.org/) though.

**Comment by RhinosF1** [comment]
Thanks anyway, i'll have a think
