### ISSUE TITLE
[stalktoy] throws an error on all IPs

### ISSUE THREAD

**Issue by Incnis-Mrsi** [Pathoschild/Wikimedia-contrib#126]
Any /meta/stalktoy/ query on an IPv4 or v6 alike fails; queries on accounts are not affected.
Apparently because an internal SQL query terminates with:
Column not found: 1054 Unknown column 'ipb_by_text' in 'field list'

The ultimate result is:
**Fatal error**: Uncaught Error: Call to a member function fetchAllAssoc() on boolean in /data/project/meta/git/wikimedia-contrib/tool-labs/stalktoy/framework/StalktoyEngine.php:415 ⋯

**Comment by Incnis-Mrsi** [comment]
Related: https://phabricator.wikimedia.org/T188327

**Comment by Pathoschild** [comment]
Fixed and deployed. Thanks for reporting it!
