### ISSUE TITLE
2019-06-23 Toolforge tools not loading

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#128]
Good day. Would it be possible to take a look at the `meta` Toolforge project? https://tools.wmflabs.org/meta and specific tools just endlesly loads but no content is actually delivered. I wonder if a webservice restart or other action is required to put the tools back up. Thanks for your help. Best regards & have a nice day.

**Comment by Pathoschild** [comment]
Done! That seems to have fixed it; not sure what the issue was.

Let me know if you want me to give you (or others trusted in the community) access to the toolforge project, so it's more likely someone will be online to handle issues like this quickly.

**Comment by MarcoAurelioWM** [comment]
> Done! That seems to have fixed it; not sure what the issue was.
> 
Thank you!

> Let me know if you want me to give you (or others trusted in the community) access to the toolforge project, so it's more likely someone will be online to handle issues like this quickly.

Feel free to add me if you want. My shell name on Toolforge is `maurelio`. Issues requiring more than a simple `webservice [...] restart` command will still need your attention though 😸.

**Comment by MarcoAurelioWM** [comment]
Reopening because at the time I'm writting this the issue previously reported is happening again.

**Comment by Pathoschild** [comment]
I see a number of "MySQL server went away" errors in the log; not sure if that's related to the issue. I restarted the service for now and added you to the maintainers. 

The current maintainers are Billinghurst, Matanya, and us; let me know if you want to suggest anyone else!
