### ISSUE TITLE
[stewardscript] Add 'Special:GlobalUserRights' link on CentralAuth

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#129]
Convenient for steward work. PR incoming (if I remember how this is done on GitHub).

**Comment by Pathoschild** [comment]
@MarcoAurelioWM Thanks for the pull request! I merged and deployed the changes, but I don't use the script myself to test it. Can you check that the changes are working fine for you?

**Comment by MarcoAurelioWM** [comment]
@Pathoschild Thanks for merging. Like I said on #130 I'm just checking Special:CentralAuth and I don't see the link. However the updated code is not yet at https://tools-static.wmflabs.org/meta/scripts/pathoschild.stewardscript.js so I guess it is just a matter of time?

**Comment by Pathoschild** [comment]
I do see the changes there; try [bypassing your cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) to get the updated code.

**Comment by MarcoAurelioWM** [comment]
> I do see the changes there; try [bypassing your cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) to get the updated code.

Yup, it's updated now. I refreshed the caché earlier to no avail so I suspect it simply took more than expected. I think this can be closed now. Thanks!

**Comment by Pathoschild** [comment]
Thanks for the PR and for testing!
