### ISSUE TITLE
Iso639dbEngine.php causing PHP errors

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#131]
I'm seeing continuous entries on `error.log` of the type:

```
2019-07-15 21:35:41: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Warning:  in_array() expects parameter 2 to be array, null given in /data/project/meta/git/wikimedia-contrib/tool-labs/iso639db/framework/Iso639dbEngine.php on line 138
```
It seems to come from: https://github.com/Pathoschild/Wikimedia-contrib/blob/588f81d71d950d317812aed6b436a39e98bdc1d2/tool-labs/iso639db/framework/Iso639dbEngine.php#L138

Regards.

**Comment by Pathoschild** [comment]
That tool didn't survive the transition to Toolforge, but I added a fix so it'll stop logging the warnings. Let me know if you notice any other issues!

**Comment by MarcoAurelioWM** [comment]
Thanks @Pathoschild - I wasn't aware the tool didn't migrated successfully. Sorry.
