### ISSUE TITLE
[stalktoy] Javascript injection is possible

### ISSUE THREAD

**Issue by Xi-Plus** [Pathoschild/Wikimedia-contrib#132]
See https://tools.wmflabs.org/meta/stalktoy/47.75.138.45 blocked column for zh.wikipedia.org. The original reason is `{{blocked proxy}}<!-- 機器人1：blocked proxy -->`, But html comment is not displayed. It is considered an HTML element. So I think script tag is the same.

**Comment by Pathoschild** [comment]
Thanks! This only affects values set by administrators, but I normalised those just in case.
