### ISSUE TITLE
pathoschild.templatescript.js violates Chrome's Content Security Policy directive

### ISSUE THREAD

**Issue by waddie96** [Pathoschild/Wikimedia-contrib#134]
`Refused to load the script 'https://tools-static.wmflabs.org/meta/scripts/pathoschild.templatescript.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self' meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

`Refused to load the script 'https://tools-static.wmflabs.org/meta/scripts/pathoschild.util.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self' meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

**Comment by Pathoschild** [comment]
See #113 for discussion.
