### ISSUE TITLE
Setup AccountElegibility event for 2020 Stewards' elections

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#135]
Requirements will be like the past year, except with the year dates. As such:

- have an account (unregistered contributors are not eligible to vote);
- not primarily use the account for automated (bot) tasks;
- have made at least 600 edits globally (on all Wikimedia wikis) before 01 November 2019;
- have made at least 50 edits globally (on all Wikimedia wikis) between 01 August 2019 and 31 January 2020.

Thank you!

**Comment by MarcoAurelioWM** [comment]
cc. @rxywm

**Comment by Pathoschild** [comment]
@MarcoAurelioWM Done! The event IDs are 51 (candidates) and 52 (voters).

I assumed...
* the candidate requirements are the same too (e.g. a sysop duration cutoff of 08 February 2020 at 14:00 UTC);
* the Meta page will be [Stewards/Elections 2020](https://meta.wikimedia.org/wiki/Stewards/Elections_2020).

See [the commit](https://github.com/Pathoschild/Wikimedia-contrib/commit/8641fa0fb1708af5374b50d8dc26b11b4b6faac0) for the specific rules, and let me know if you want to change anything.

**Comment by MarcoAurelioWM** [comment]
Thank you! We're still drafting the calendar. So far it does not look like
we will changing the dates but please allow me a week or two to close this
with my fellow stewards. Best regards.

>

**Comment by MarcoAurelioWM** [comment]
Sorry that it took so long to reply back. Dates as posted originally might
need to be changed. It looks we've agreed the definitive ones at
https://meta.wikimedia.org/wiki/Stewards/Elections_2020. Can the tool be
updated to reflect the new dates, please? Thanks!

>

**Comment by Pathoschild** [comment]
@MarcoAurelioWM The page seems to have the same dates I used. Here are the current rules if you want to change any specific ones.

* Voters:
   * no bot flag on any wiki;
   * 600 edits across all wikis before 01 November 2019 at 00:00 UTC;
   * 50 edits across all wikis between 01 August 2019 at 00:00 UTC and 31 January 2020 at 23:59:59 UTC.
* Candidates:
  * same rules as voters;
  * sysop for at least three months before 08 February 2020 at 14:00 UTC;
  * extra requirements:
    > * You must be 18 years old, and at the age of majority in your country.
    > * You must agree to abide by the policies governing [steward access](https://meta.wikimedia.org/wiki/Stewards_policy), [checkuser access](https://meta.wikimedia.org/wiki/CheckUser_policy), [oversight access](https://meta.wikimedia.org/wiki/Oversight_policy), and [privacy](https://foundation.wikimedia.org/wiki/Privacy_policy).
    > * You must [sign the confidentiality agreement](https://meta.wikimedia.org/wiki/Special:MyLanguage/Access_to_nonpublic_personal_data_policy).

**Comment by MarcoAurelioWM** [comment]
Looks good to me. Thanks!
