### ISSUE TITLE
Upgrading URLs due to the introduction of the `toolforge.org` domain

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#137]
Due to the introduction of the `toolforge.org` domain (_See_ [News/Toolforge.org](https://wikitech.wikimedia.org/wiki/News/Toolforge.org), [[Cloud] Toolforge: new domain toolforge.org](https://lists.wikimedia.org/pipermail/cloud/2020-May/001079.html) and [Task T234617](https://phabricator.wikimedia.org/T234617), the following code is returning a `404` when used in `Special:CheckUser`:

https://github.com/Pathoschild/Wikimedia-contrib/blob/0561be75e2138b3dbc57053722ed4ddde25e0877/user-scripts/pathoschild.stewardscript.js#L254

It looks like the server redirect they've placed is rewritting https://tools.wmflabs.org/pathoschild-contrib/stalktoy/ to https://pathoschild-contrib.toolforge.org/stalktoy/ which does not exist.

Notwithstanding any other references that may need to be upgraded, if any; I'll be submitting a Pull Request to address that line of the code. It should be updated in the `tools-static` directory as well.

Thank  you!

**Comment by Pathoschild** [comment]
Thanks for the PR! The redirect from `pathoschild-contrib` is part of my test changes to support the new subdomains. Nothing should be linking to that account, since it's meant for testing and internal tools. Since the link is fixed, I'll close this in favor of #139.
