### ISSUE TITLE
Stalktoy unable to query data

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#148]
Hello:

https://meta.toolforge.org/stalktoy is not working today. I'm attaching two screenshots of the two errors displayed.

Note: the IPs displayed are intentionally fake for privacy purposes. Errors were spotted with real ones.

![stalktoy_bug_20210515_1](https://user-images.githubusercontent.com/30000615/118358551-94fcc680-b57f-11eb-82a0-0d63775b5a51.png)
![stalktoy_bug_20210515_2](https://user-images.githubusercontent.com/30000615/118358550-94643000-b57f-11eb-9375-a548fb855e16.png)

Also, with regards to the first screenshot, the issue seems not limited to `s6.web.db.svc.eqiad.wmflabs` as retrying failed too on all others `s.*` databases.

Thank you for your assistance.

Best regards.

**Comment by Pathoschild** [comment]
Related links:
* [Wiki Replicas 2020 Redesign](https://wikitech.wikimedia.org/wiki/News/Wiki_Replicas_2020_Redesign)
* [Phabricator issue T282895: _https://meta.toolforge.org/stewardry/srwiki?bureaucrat=1 raises exception: SQLSTATE[HY000] [1049] Unknown database 'srwiki_p'_](https://phabricator.wikimedia.org/T282895)

**Comment by Pathoschild** [comment]
Fixed via 2284afdf5e3c91b67f7def7a57166a9514dbb2a5 and deployed. Thanks for reporting it!

**Comment by MarcoAurelioWM** [comment]
Thanks for the quick fix. It works again 😃
