### ISSUE TITLE
JQMIGRATE warnings for $.isArray and $.isFunction

### ISSUE THREAD

**Issue by inductiveload** [Pathoschild/Wikimedia-contrib#150]
On enwikisource, I'm seeing JQMIGRATE console warnings due to

https://github.com/Pathoschild/Wikimedia-contrib/blob/2284afdf5e3c91b67f7def7a57166a9514dbb2a5/user-scripts/pathoschild.templatescript.js#L964

(though that is not the only use of `$.isArray`)

```
JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray
```

I _think_ it's a simple change to `Array.isArray( opts )` (and similar for the others).

Similarly: `JQMIGRATE: jQuery.isFunction is deprecated` from

https://github.com/Pathoschild/Wikimedia-contrib/blob/2284afdf5e3c91b67f7def7a57166a9514dbb2a5/user-scripts/pathoschild.templatescript.js#L804

which is the same as `typeof opts.script === "function"`

**Comment by Pathoschild** [comment]
Fixed; thanks for reporting it! (It may take a few hours for the server cache to update, in addition to your browser's cache time.)

**Comment by he7d3r** [comment]
@Pathoschild Should this issue be closed?

**Comment by Pathoschild** [comment]
Yep, I haven't seen any more reports about it.
