### ISSUE TITLE
[Account Elegibility] Steward elections 2022

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#157]
Elegibility criteria for **candidates**
- be eligible to vote as outlined below;
- hold or have held administrator rights on at least one public Wikimedia Foundation project for a period of at least three months

Elegibility criteria for **voters** (same as last year, but different dates)

- have an account;
- not primarily use the account for automated (bot) tasks;
- have made at least 600 edits globally (on all Wikimedia wikis) before 01 November 2021;
- have made at least 50 edits globally (on all Wikimedia wikis) between 01 August 2021 and 31 January 2022.

I'll attempt a pull request.

**Comment by Pathoschild** [comment]
Merged and deployed via #158. Thanks for the PR!
