### ISSUE TITLE
[AccountEligibility] Request addition of UCOC EG voter eligibility

### ISSUE THREAD

**Issue by Xeno-WMF** [Pathoschild/Wikimedia-contrib#161]
https://meta.wikimedia.org/wiki/Universal_Code_of_Conduct/Enforcement_guidelines/Voter_information#Voting_eligibility

Eligibility criteria -
    not be blocked in more than one project;
    and not be a bot;
    and have made at least 300 edits before 7 February 2022 across Wikimedia wikis;
    and have made at least 20 edits between 7 August 2021 and 7 February 2022.
    
( This is the same as https://meta.toolforge.org/accounteligibility/56 except for the dates which have changed. )

Thank you in advance, and for your ongoing work on this tool!

**Comment by Pathoschild** [comment]
Done! See [event 62](https://meta.toolforge.org/accounteligibility/62), and let me know if you notice any issues or want to change anything.
