### ISSUE TITLE
Tool "Stalk toy" doesn't work correct.

### ISSUE THREAD

**Issue by Dusan-Krehel** [Pathoschild/Wikimedia-contrib#164]
**What is bad?**

- If i open the someone user of Stalk toy (https://meta.toolforge.org/stalktoy/), i don't see right result.

**How is right?**

- Fixed or change SQL query.

**See also**
* https://phabricator.wikimedia.org/T304986

**Comment by Pathoschild** [comment]
Hi! That's not a bug with Stalktoy, it's an issue with the Toolforge infrastructure. You can watch [T304733](https://phabricator.wikimedia.org/T304733) for updates on that. Once that ticket is fixed, Stalktoy should work fine again.

**Comment by Pathoschild** [comment]
This still isn't fixed, so I added a banner on the Stalktoy page for now.
