### ISSUE TITLE
stalktoy: Wikitech (labswiki) is not a SUL wiki

### ISSUE THREAD

**Issue by supertassu** [Pathoschild/Wikimedia-contrib#165]
See for example [stalktoy for my account](https://meta.toolforge.org/stalktoy/?target=Majavah&show_all_wikis=on). Wikitech is not a SUL wiki, so stalktoy should not tell me to attach that account.
![image](https://user-images.githubusercontent.com/9721638/168461458-4545e3d0-760c-4b96-8b43-4c43b37cd5e4.png)

**Comment by bd808** [comment]
After https://www.mediawiki.org/wiki/SUL_finalisation was done I wonder if there is any real value in that prompt at all? It should no longer be possible to have a local account on any actual SUL wiki that is not also a global account.

**Comment by Pathoschild** [comment]
Fixed! The list of non-unifiable wikis was out of date.

I don't think unifiable local accounts are possible anymore, but the message is still useful to double-check if the edge case ever comes up.
