### ISSUE TITLE
[AccountEligibility] BoT 2022 "edits between" end date is wrong

### ISSUE THREAD

**Issue by plstand** [Pathoschild/Wikimedia-contrib#170]
Per foks's comment at https://gerrit.wikimedia.org/r/c/mediawiki/extensions/SecurePoll/+/813346/1/cli/wm-scripts/bv2022/populateEditCount.php#24:

> Elections Committee says July 5 should be included. Last year's reading of the criteria seems to have been incorrect.

**Comment by Pathoschild** [comment]
Merged and deployed via #171. Thanks for the help!
