### ISSUE TITLE
[AccountEligibility] Enkhsaihan2005's eligibility information for SE2023 candidates seems to be incorrect

### ISSUE THREAD

**Issue by urbanecm** [Pathoschild/Wikimedia-contrib#175]
[Eligibility information for Enkhsaihan2005](https://meta.toolforge.org/accounteligibility/?event=66&user=Enkhsaihan2005) claim:

On [bxr.wikipedia.org](https://bxr.wikipedia.org/wiki/User:Enkhsaihan2005):
* is not a bot...
* has at least 600 edits as of 31 October 2022 (has 12846 so far).
* has at least 50 edits between 01 August 2022 and 31 January 2023 (has 86 so far).
* was not flagged as a sysop for a continuous period of at 90 days as of 30 January 2023 (longest flag duration was 75 days)...

The last statement seems to be incorrect, see [Meta logs](https://meta.wikimedia.org/wiki/Special:Log?type=&user=&page=User%3AEnkhsaihan2005%40bxrwiki&wpdate=&tagfilter=&wpfilters%5B%5D=newusers&wpFormIdentifier=logeventslist):

> [21:57, 23 November 2021](https://meta.wikimedia.org/w/index.php?title=Special:Log&logid=44542340) [Ruslik0](https://meta.wikimedia.org/wiki/User:Ruslik0) [talk](https://meta.wikimedia.org/wiki/User_talk:Ruslik0) [contribs](https://meta.wikimedia.org/wiki/Special:Contributions/Ruslik0) changed group membership for [Enkhsaihan2005@bxrwiki](https://bxr.wikipedia.org/wiki/User:Enkhsaihan2005) from (none) to administrator (temporary, until 22:57, 23 May 2022) (per [request](https://meta.wikimedia.org/wiki/Special:Permalink/22370286))

As far as I can see, Enkhsaihan2005 was a bxrwiki admin between at least November 23, 2021 and May 23, 2022 (180 days).

The tool's information (75 days) seems to be about their most recent adminship (which ranged from May 24, 2022 to August 08, 2022), not the longest flag duration. Can this be investigated please?

**Comment by Superpes15** [comment]
I noticed that the same problem, even if it's irrelevant, concerns me. Only the duration of my most recent flag [is reported](https://meta.toolforge.org/accounteligibility/66/Superpes15?wiki=itwiki), but I actually had a longer one previously, therefore the "longest flag durations" information is incorrect (because it refers only to the last term). Best

**Comment by Pathoschild** [comment]
Fixed. Can you confirm the info looks correct for both users now?

**Comment by urbanecm** [comment]
Looks good now! Thanks for the quick fix. Closing.
