### ISSUE TITLE
[AccountEligibility] add Universal Code of Conduct Coordinating Committee special election

### ISSUE THREAD

**Issue by kpeterzell** [Pathoschild/Wikimedia-contrib#184]
Please add the Universal Code of Conduct Coordinating Committee special election to the events:

*  [Special election landing page](https://meta.wikimedia.org/wiki/Universal_Code_of_Conduct/Coordinating_Committee/Election/2024_Special_Election
)
* [Special election voter eligibility criteria](https://meta.wikimedia.org/wiki/Universal_Code_of_Conduct/Coordinating_Committee/Election/2024_Special_Election/Voter_eligibility_criteria)

**Comment by Pathoschild** [comment]
Done and deployed!
