### ISSUE TITLE
[synchbot] Publish source code

### ISSUE THREAD

**Issue by Krinkle** [Pathoschild/Wikimedia-contrib#41]
https://meta.wikimedia.org/wiki/Synchbot says it's part of Wikimedia-contrib and links here. Is it run from tool-labs by people with access to the 'meta' tool labs project? Or by you from your local computer? Either way, would be interesting to potentially have other users be able to run it as well (or even just inspect its source code; or to take over in case you disappear).

**Comment by Pathoschild** [comment]
@Krinkle: if you're still interested in getting access, contact me privately and I'll set you up with the source code and information on how to use it. :)
