### ISSUE TITLE
Stewardry doesn't count imported edits for last edit

### ISSUE THREAD

**Issue by nemobis** [Pathoschild/Wikimedia-contrib#43]
https://tools.wmflabs.org/meta/stewardry/mediawikiwiki?bureaucrat=1  thinks IAlex last edited on 2006-12-21, while it's actually been few days.

It might matter that the edit in question was actually imported (see https://www.mediawiki.org/w/index.php?title=Manual:Pywikibot/interwiki.py/fr&action=history ) and perhaps also that there were no edits on mediawiki.org until a year later. https://www.mediawiki.org/w/index.php?title=Special:Contributions&dir=prev&offset=20061221200000&tagfilter=&contribs=user&target=IAlex&namespace=

**Comment by Pathoschild** [comment]
Fixed by #44.
