### ISSUE TITLE
[stalktoy] Edit count is sorted alphabetically

### ISSUE THREAD

**Issue by WikimediaDoug** [Pathoschild/Wikimedia-contrib#48]
Attempting to sort the stalktoy table by number of edits, I get the following top 10 results:

wiki edits registered groups unified login block 
frwikisource  97  2010-12-07 15:17  unified   
commonswiki  934  2008-03-10 04:01 Image-reviewer, filemover unified   
ruwikisource  9  2011-02-11 06:11  unified   
jawiki  9  2008-11-21 02:51  unified   
kowiki  8  2008-11-21 02:32  unified   
eswiki  7  2011-08-26 19:47  unified   
cawikisource  7  2011-02-11 05:47  unified   
elwikisource  7  2011-02-12 17:31  unified   
sourceswiki  627  2010-12-03 17:16 import, sysop unified   
ptwikisource  6  2010-12-04 19:52  unified   

and so on.  enwiki, enwikisource, etc, where I have far more edits, are way down the list.  It's sorting by the left most place, then the next place, rather than by the value of the complete number, thus if one has 99 edits, it will be above one with 98000 edits.

https://tools.wmflabs.org/meta/stalktoy/Doug

**Comment by Pathoschild** [comment]
The sorting is correctly numerical for me in Chrome and IE11. Are you using a different browser?

**Comment by Pathoschild** [comment]
Unable to reproduce.
