### ISSUE TITLE
[regex editor] Add search autocompletion and replace autosaving

### ISSUE THREAD

**Issue by alexbrollo** [Pathoschild/Wikimedia-contrib#58]
It would be useful to implement into Regex Editor:
1. a self-completing feature into search field, showing matching search strings into saved session/sessions;
2. when search string matches exactly a stored regex search, replace field should be filled with stored replace string, and its edited value  should be saved into session overwriting the previous data. 

So, Regex editor would be converted into a Regex session editor.

**Comment by Pathoschild** [comment]
Thanks for the suggestion. It's a very interesting idea, but I don't think it fits _as a default feature_ of the regex editor for three reasons:
* One of the wishlist features is syntax autocompletion. (You can see an example at [regex101.com](https://regex101.com/#javascript) by typing `[`, or selecting some text and typing `[` to surround it.) Having both types of autocompletion would be confusing.
* When you have sessions with several search & replace patterns, each search can depend on the previous patterns. That means the same search can have very different effects in each session, so autocompletion would be counterintuitive. (This is one of the main use cases.)
* Automatically rewriting saved sessions based on pattern similiarity may be detrimental, especially with multi-pattern sessions. When loading a previous session, there'd be no guarantee it hasn't been transparently changed without your knowledge.

Although this doesn't fit the generic use cases, that doesn't mean your use case is invalid. If this is something you need, I could add events or hooks to regex editor which let you add custom behaviour for your needs. You would need to implement your custom behaviour yourself (or find someone who can), though.

**Comment by alexbrollo** [comment]
Thanks for appreciation and comments.
While Samuele is working about TemplateScript into itsource (it will be a
hard job, you can't imagine how many scripts and variables are running *into
the global space* :-( , something like a bazaar...), I'll try to add a
similar feature into Candalua's Regex Editor (into mul.source, I'll avoid
any edit into it.source...), that feeds our "memoRegex" and that works at
one "session" only at a time; as I told you, regex are saved as objects,
not as arrays, search field being the key, and that structure perhaps will
simplify the job. I'll try to add a popup to choose the regex that needs
edit.

Alex

2015-08-22 21:45 GMT+02:00 Jesse Plamondon-Willard <notifications@github.com

**Comment by alexbrollo** [comment]
Thanks. My experience is limited to unique sessions per work, managed by few bold users; so I didn't imagine the true complexity of a generalized, multi-session tool.
