### ISSUE TITLE
[TemplateScript] use mw.* helpers for configuration in 2.0

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/Wikimedia-contrib#65]
The user can turn off the regex editor like this:

```javascript
var pathoschild = pathoschild || {};
pathoschild.disableRegexEditor = true;
```

TemplateScript should use the new `mw.user.options`. This will let the user do this instead:

```javascript
mw.user.options.set('pathoschild.templatescript', { regexEditor: false });
```

**Comment by Pathoschild** [comment]
Done!

**Comment by Pathoschild** [comment]
In 9c75a24 @he7d3r notes:
> Due to lack of documentation, I'm not sure if `mw.user.options` is an instance of `mw.Map` which is supposed to be used for anything other than user preferences having a corresponding key in MW's
https://meta.wikimedia.org/w/api.php?action=query&meta=userinfo&uiprop=options

I reopen this ticket to make sure.

**Comment by Pathoschild** [comment]
It's fine as long as we respect some constraints. Quoting from [_mw:Api:Options#Changing options_](https://www.mediawiki.org/wiki/API:Options#Changing_options):
> While this API is primarily intended for changing options which are registered by MediaWiki core or extensions and available on Special:Preferences, since [Gerrit #I5f9ba5](https://gerrit.wikimedia.org/r/#/q/I5f9ba5b0,n,z) you can also use it to set arbitrary user options that can be used by user-scripts or external editors.
> 
> These arbitrary options have three limits imposed on them:
> * the key must start with the prefix `userjs-`
>* the length of the key must not be more than 255 bytes
> *the key must consist only of ASCII letters, numbers, hyphens and underscores (a-z, A-Z, 0-9, _, -)
> 
> There are currently no hard limits on the length or contents of the value, nor is there a limit on the number of user options you can set at once. You can even store a complex tree of data within a user option by encoding it as a JSON string.

**Comment by he7d3r** [comment]
That is not exactly what I mean. I suspect we are only supposed to use `mw.user.options.get()`, as it is MediaWiki which sets its values when someone loads ResourceLoader's "user.options" module.

Are you planning to set "userjs-templatescript" though the api, so that the value is really saved to the user preferences? (e.g. with a mw.Api() call to action=tokens&type=options)
Otherwise, people might get confused by the fact that some of the mw.user.options.values will not match what they get from the server through
https://meta.wikimedia.org/w/api.php?action=query&meta=userinfo&uiprop=options

**Comment by Pathoschild** [comment]
For now our use case is setting options right before you load the script. I don't think we need to persist that to the API, and doing so might even be confusing (since removing the line from the user's `*.js` would have no effect). At some point we might want a UI to configure options instead, in which case persisting to the API would make more sense.

If the user knows enough about MediaWiki scripting to notice that the userinfo API doesn't return the TemplateScript configuration key, they'd probably also know why. :)

**Comment by ricordisamoa** [comment]
I think `mw.user.options` should only be used after saving preferences on the server side, for example with `mw.Api#saveOptions`.

**Comment by he7d3r** [comment]
MediaWiki has two instances of `mw.Map`. If there is no intention of making the user option to be saved, then you can simply use `mw.config` (which has no dependency) instead of `mw.user.options` (whose functionality is provided by the ResourceLoader module "user.options") to `.set()` an option right before the script is loaded:
```javascript
mw.config.set('templatescript-foo-bar', { regexEditor: false });
```
That would make things less confusing.

**Comment by ricordisamoa** [comment]
Or better yet, create a separate instance of `mw.Map`.
```javascript
pathoschild.TemplateScript.config.set('regexEditor', false);
```

**Comment by Pathoschild** [comment]
@ricordisamoa: unfortunately that would need TemplateScript to be loaded before you can define your settings, by which point it would be too late to configure the initialisation.

This is fundamentally what `mw.user.options` is for: a generic way to get and store user settings. They don't necessarily need to be persisted to the API. To make sure, I asked whether this was a valid use of `mw.user.options` in [#mediawiki](https://www.mediawiki.org/wiki/MediaWiki_on_IRC), to which [Legoktm says yes](https://meta.wikimedia.org/wiki/Special:Diff/13350424).

By contrast, here's what [Krinkle said in 2011](https://static-bugzilla.wikimedia.org/show_bug.cgi?id=30783#c12) about doing the same with `mw.config`:
> Please don't extend the mw.config objects, certainly not for purposes that is not related to MediaWiki's configuration object at all

**Comment by he7d3r** [comment]
I think Krinkle's comment is more about not setting `mw.config.<anything>` than about setting a new value with `mw.config.set( '<the new value>' )`.

**Comment by Pathoschild** [comment]
I discussed this in #mediawiki to see which is preferred. Looks like `mw.config` wins after all. :)

> **Pathoschild:** Hi! I want to let users configure a user script in their personal \*.js (where the configuration isn't saved to the API). Is there a preference between mw.config.set(...) and mw.user.options.set(...) for that?
> **Katie:** Pathoschild: Why not saved?
> **Katie:** Maybe a cookie or localStorage? Not sure what you're trying to do, though.
> **Vulpix:** https://www.mediawiki.org/wiki/ResourceLoader/Modules#jquery.jStorage
> **Pathoschild:** I have a script that users can configure right before it's loaded. Something like this:
> **Pathoschild:** mw.user.options.set('userjs-templatescript', { regexEditor: false }); mw.loader.load(...);
> **Pathoschild:** I think persisting the config (whether to cookies, localstorage, or the API) would be confusing, since removing the line afterwards would have no effect. It's really meant to set configuration only for the current context (previously they'd set a variable before calling the script).
> **Pathoschild:** Both work (since I'm just adding a value to the map), but I don't want to use them inappropriately. :)
> **Vulpix:** so you want to just store a global variable during the execution of the script... yes, that's fine. I think mw.config.set(...) should be preferred
> **Pathoschild:** Thanks. Are there any conventions for custom mw.config settings (like prefixing the key with "userjs-")?
> **ori:** Pathoschild: I don't think so. But that's a good idea ("userjs-").

I'll make the change in 2.0, since that's the next release.

**Comment by Pathoschild** [comment]
Done in the 2.0 branch.

**Comment by Pathoschild** [comment]
Merged into `master` and pushed live.
