### ISSUE TITLE
[TemplateScript] add script helpers for arbitrary fields in 2.0

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/Wikimedia-contrib#68]
Some wikis have extra fields that need to be edited by custom scripts. For example, [pages on enwikisource](https://en.wikisource.org/wiki/Page:LA2-NSRW-1-0187.jpg?action=edit) have a header and footer that is often generated from custom scripts. The custom scripts need to use jQuery to edit the fields directly, which means they can't use the shorthand methods like `editor.replaceSelection`, `editor.append`, etc.

Implement a way for custom scripts to use the helpers with arbitrary fields.

**Comment by Pathoschild** [comment]
Done in the 2.0 branch. The `editor` now lets you get the generic helpers for any text input (except `escape` and `unescape` for now):

```javascript
editor.for('#wpHeaderTextbox')
   .set('...')
   .prepend('...')
   .append('...')
   .replace(/.../g, '...')
   .replaceSelection(...)
   .get();
```

(Note that `editor.for('#wpTextbox1')` is not equivalent to `editor`, because the latter has non-generic logic like abstracting [CodeEditor](https://www.mediawiki.org/wiki/Extension:CodeEditor).)

**Comment by Pathoschild** [comment]
Merged into `master` and pushed live.

**Comment by Pathoschild** [comment]
Reopened per @he7d3r's inline comment on 6daa07b:
> @Pathoschild : Unfortunately this name can't be used in user scripts, due to [T96901](https://phabricator.wikimedia.org/T96901). Here is a minimal example which causes 
>> JavaScript parse error: Parse error: Unexpected token; token 3 expected in file 'User:He7d3r/global.js' on line 6

> https://meta.wikimedia.org/w/index.php?title=User:He7d3r/global.js&oldid=13382609

**Comment by Pathoschild** [comment]
Alright. So what's a good alternative name that's intuitive and concise?

```javascript
editor.for('#wpSummary').append('T96901'); // for comparison
editor.over('#wpSummary').append('T96901');
editor.on('#wpSummary').append('T96901');
editor.around('#wpSummary').append('T96901');
editor.forField('#wpSummary').append('T96901');
editor.wrap('#wpSummary').append('T96901');
```

**Comment by he7d3r** [comment]
I like `forField` (btw: does it accept `forField('.multiple #elements')`?).

**Comment by Pathoschild** [comment]
@he7d3r: `forField` is meant to wrap one element, and the [behaviour is undefined](https://en.wikipedia.org/wiki/Undefined_behavior) if you give it multiple. That said, it will mostly work just fine on multiple elements, except that `get()` will return the value of the first element (per jQuery behaviour) and `replaceSelection` will only work on the first element (even if you selected text in another field).

To avoid any issues, though, we should either fully support multiple elements or explicitly not support them (by adding `.first()` to the selector). Is there a known use case for wrapping multiple fields with an editor?

**Comment by he7d3r** [comment]
Probably not. I was just wondering because for many elements "forField**s**" would make more sense. But I didn't see any use of that so far. I think it would be good idea to add `.first()`.

**Comment by Pathoschild** [comment]
Done and pushed live. All usages have been updated.
