### ISSUE TITLE
[TemplateScript] support shared libraries

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/Wikimedia-contrib#72]
Consider adding built-in support for importing shared libraries of TemplateScript scripts and templates.

### The problem
TemplateScript scripts often have a few maintainers and many users. Since there's no built-in way to import scripts and templates, sharing is usually done in one of these two ways.

Many users simply copy & paste entire scripts. For example, [at least 29 users duplicated an OCR cleanup script on enwikisource](https://en.wikisource.org/wiki/Special:Search?profile=all&search=%22stuff+to+do+only+if+the+page+doesn%27t+contain%22). This is the worst solution for all concerned: there are many versions in use, it's much harder to maintain, and once copied it's typically no longer updated when the maintainer improves it.

Maintainers can address these limitations by packaging their scripts for reuse. For example, [at least 388 users](https://en.wikipedia.org/wiki/Special:Search?search=%22User%3AOhconfucius%2Fscript%2FMOSNUM%20dates.js%22%20intitle%3A.js&profile=all) use [Ohconfucius' MOSNUM dates scripts](https://en.wikipedia.org/wiki/User:Ohconfucius/script/MOSNUM_dates) on enwiki by [adding one line to their user scripts](https://en.wikipedia.org/wiki/User:Ohconfucius/script/MOSNUM_dates#Installing_the_script). This is a pretty good solution (and [it's recommended in the TemplateScript documentation](https://meta.wikimedia.org/wiki/TemplateScript#As_a_gadget_or_framework)), but it doesn't allow any flexibility. You get every script even if you only use a few of them:
> ![image](https://cloud.githubusercontent.com/assets/230581/9922881/c4376fb8-5cbb-11e5-8b8e-aad30794d992.png)

If you want to add a subset of those scripts or move them into a custom sidebar, your only option is to duplicate the scripts, or import the methods and register them manually with TemplateScript.

### Solutions?
Since this is a very common way of using TemplateScript, can we make this easier? For example, it would be great if users could do this:

```javascript
// load all scripts
pathoschild.TemplateScript.importLibrary('User:Ohconfucius/script/MOSNUM_dates.js');

// load a subset of scripts
pathoschild.TemplateScript.importLibrary('User:Ohconfucius/script/MOSNUM_dates.js', ['all-to-dmy', 'all-to-mdy']);
```

Or maybe even this:
```javascript
// completely customise how scripts are imported
pathoschild.TemplateScript.importLibrary('User:Ohconfucius/script/MOSNUM_dates.js', function(library) {
   library
      .disable('*')
      .enable(['all-to-dmy', 'all-to-mdy'])
      .configure('*', {
         category: 'convert dates' // override category for all scripts
      })
      .configure('all-to-mdy', {
         name: 'US format' // overrides name for the specified script
      });
});
```

Is this a problem we should address, and how should we solve it?

**Comment by billinghurst** [comment]
To be radical the best way that I see is the ability for a community to
have a special: page for their scripts that gives the ability to the user
to tick on and off those they wish to use.

OR

For the WSes that they can have scripts tied to works in the Index/Page ns
that dynamically apply based on the work, without the need for the user to
activate anything.

Getting away from anything geeky, to something user friendly is my
preference.

Regards Billinghurst

**Comment by Pathoschild** [comment]
I like it. The special page would be much more user-friendly, and it could be used to configure other TemplateScript settings too. I guess [we'd save to the user's preferences](https://www.mediawiki.org/wiki/API:Options).

The second suggestion is a good idea too, but it's really a separate feature.

**Comment by Pathoschild** [comment]
Here's a quick mockup of @billinghurst's idea:
![image](https://cloud.githubusercontent.com/assets/230581/9974193/a9a20fda-5e52-11e5-8e96-f79aaf598c6e.png)

I really like this approach so far. Any thoughts?

**Comment by Pathoschild** [comment]
A hidden prototype is now live; you can see the settings UI by visiting `Special:TemplateScript` on any wiki. Here's how it works (continuing the previous examples):

1. The script maintainer's shared `mosnum-dates.js` contains this code:

    ```javascript
    pathoschild.TemplateScript.library.define({
        key: 'ohc.dates',
        name: 'MOSNUM date conversions',
        url: '//en.wikipedia.org/wiki/User:Ohconfucius/script/MOSNUM dates',
        description: 'A set of scripts by <a href="//en.wikipedia.org/wiki/User:Ohconfucius">Ohconfucius</a> that convert dates in an article between different formats compatible with <a href="//en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Dates_and_numbers">Wikipedia:Manual of Style/Dates and numbers</a>.',
        categories: [
            {
                name: 'Date conversions',
                scripts: [
                    { key: 'all-to-dmy', name: 'ALL dates to dmy', script: example },
                    { key: 'body-to-dmy', name: 'Body dates to dmy', script: example },
                    { key: 'body-to-mdy', name: 'Body dates to mdy', script: example },
                    { key: 'body-pub-to-dmy', name: 'Body+pub dates to dmy', script: example },
                    { key: 'body-pub-to-mdy', name: 'Body+pub dates to mdy', script: example },
                    { key: 'iso-to-dmy', name: 'ISO to dmy', script: example },
                    { key: 'iso-to-mdy', name: 'ISO to mdy', script: example },
                    { key: 'access-to-iso', name: 'access 2 ISO', script: example },
                    { key: 'del-year-in-x', name: 'Del year-in-X dates', script: example },
                    { key: 'expand-ref-dates', name: 'Expand ref dates', script: example },
                    { key: 'expand-all', name: 'Expand all dates', script: example },
                    { key: 'abbrev-ref', name: 'Abbrev ref dates', script: example },
                    { key: 'us-slash', name: 'US-slash dates', script: example },
                    { key: 'uk-slash', name: 'UK-slash dates', script: example }
                ]
            }
        ]
    });
    ```
2. The user imports it the usual way via `common.js` (or a gadget):

    ```javascript
    mw.loader.load('[url]/mosnum-dates.js');
    ```

    If they do nothing else, all scripts are automatically enabled.

3. When the user visits `Special:TemplateScript` on the wiki, they see the UI shown in my previous comment. They can uncheck scripts they don't want, and their changes will automatically save to their user preferences.

To do:

1. Discuss! Here's your chance to influence how the feature works.
2. Rewrite [Wikisource:TemplateScript](https://en.wikisource.org/wiki/Wikisource:TemplateScript) to use this new feature (they're made for each other).
3. Translate the new UI.
4. When it's ready for general use, add a **⚙** link to the TemplateScript menu.

**Comment by Pathoschild** [comment]
I added an optional `defaultEnabled` flag to support preloading libraries. When a library has `defaultEnabled: false`, none of its scripts will be enabled unless the user explicitly selects them via `Special:TemplateScript`.

This is mainly meant for wikis like enwikisource that have some scripts that are widely useful. For example, this lets you create one TemplateScript gadget which comes preloaded with a set of useful scripts, and the user can choose the ones they want via [[Special:TemplateScript]] without worrying about enabling multiple gadgets or manually importing any scripts.

This is still a hidden experimental feature, so it's open to change. (For example, would it be useful to choose whether individual scripts are enabled by default?)

**Comment by Pathoschild** [comment]
The feature is now live, with the first libraries being rolled out on enwikisource. I'll mark this done.
