### ISSUE TITLE
[tool-labs] Open source license

### ISSUE THREAD

**Issue by ricordisamoa** [Pathoschild/Wikimedia-contrib#79]
https://wikitech.wikimedia.org/wiki/Nova_Resource:Tools/Rules
> All code in the tools project must be published under an OSI approved open source license

https://wikitech.wikimedia.org/wiki/Help:Tool_Labs/Right_to_fork_policy
> All Tool Labs hosted tools must license their source code under an OSI approved FLOSS software license.

No Creative Commons license seems listed [here](//opensource.org/licenses/alphabetical)

**Comment by Pathoschild** [comment]
That's ironic, since the OSI content is licensed under a Creative Commons license. I'd like to find out more about the OSI's stance on Creative Commons licenses before I look into relicensing.

**Comment by Pathoschild** [comment]
Scratch that; I changed to the MIT license since that's what I normally use anyway. :)

**Comment by ricordisamoa** [comment]
Thank you :)
Further reading at https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
