### ISSUE TITLE
[StewardScript] AJAX CheckUser?

### ISSUE THREAD

**Issue by ghost** [Pathoschild/Wikimedia-contrib#82]
StewardScript contained previously an AJAX checkuser function. After being missing from sometime already, I wonder if that function could return to the stewardscript or if the issues that made this to be removed are still present thus blocking its re-addition. Best regards.

**Comment by Pathoschild** [comment]
Hi @maurelio-wm. I don't think any of these scripts ever had an ajax checkuser feature; maybe that was from someone else's script?

**Comment by maurelio-wm** [comment]
Hi @Pathoschild If you check [this oldid](https://meta.wikimedia.org/w/index.php?title=StewardScript&oldid=2425572) you'll see that your steward script did supported that feature in the past. Unfortunately I cannot find the page where the source code of StewardScript was previously located to link it to you. I'll dig deeper. Regards.

**Comment by maurelio-wm** [comment]
Was called "instant checkuser" at [this source](https://meta.wikimedia.org/w/index.php?title=Special:Undelete&target=User%3APathoschild%2FScripts%2FStewardScript.js&timestamp=20120227014946) (page deleted) and you said you had to disable it since Wikimedia set X-Frame-Options DENY. Regards.

**Comment by Pathoschild** [comment]
Thanks for digging that up. Unfortunately those reasons still apply: we still don't have a crosswiki userrights API, and the wiki APIs don't set `Access-Control-Allow-Origin` headers which would let scripts call the userrights API on the target wiki.

**Comment by he7d3r** [comment]
Is there a Phabricator task about that yet?

**Comment by maurelio-wm** [comment]
@he7d3r No as far as I know.

@Pathoschild Thanks for your reply. Maybe @tgr could weight in (is anomie here?) and see if it is worth requesting this setting to be back?

Thanks.

**Comment by tgr** [comment]
MediaWiki does set CORS headers. See https://www.mediawiki.org/wiki/Manual:CORS for details.

**Comment by tgr** [comment]
Alternatively you could use the centralauthtoken API. CORS is somewhat fragile in that you might not be logged in on the target wiki.

**Comment by maurelio-wm** [comment]
@Pathoschild does @tgr points help you? Regards.

**Comment by Pathoschild** [comment]
Hi @maurelio-wm. I no longer actively develop StewardScript since I'm no longer a steward. If someone submits a pull request, I'd be happy to review + merge + deploy it though. :)

**Comment by Pathoschild** [comment]
I'm no longer very active on Wikimedia wikis, so I'm not actively developing new features for these scripts. (I'm still maintaining the existing scripts though.) I'll close this as _won't do_, but pull requests are welcome if someone wanted to tackle this.
