### ISSUE TITLE
[StewardScript] Change of prefilled reasons, add some more

### ISSUE THREAD

**Issue by ghost** [Pathoschild/Wikimedia-contrib#83]
Currently "crosswiki abuse" is the only reason that is prefilled by the script, no matter if we select "lock", "lock & hide" or "lock & oversight". It'd be good if, depending on the option, the message could also change. I propose to keep "crosswiki abuse" for "lock" but:

- for "lock & hide" I'd go with "offensive or abusive username" (except a better proposed wording).
- for "lock & oversight" I'd go with "blatant attack username" (wording from OS policy).

Also, it'd be good if we could get some "lock (spambot)" and "lock (lta)" with "spambot" and "long term abuse" reasons respectivelly added to the menu. Those are the most used summaries for now and will save us few clicks as well.

I've looked at the code and tried to do that myself, but it doesn't look trivial enough for me.

Thank you.

**Comment by maurelio-wm** [comment]
Ping :)

**Comment by Pathoschild** [comment]
Hi @maurelio-wm. I no longer actively develop StewardScript since I'm no longer a steward. If someone submits a pull request, I'd be happy to review + merge + deploy it though. :)

**Comment by MarcoAurelioWM** [comment]
@Pathoschild Hi. Unfortunately my JS skills are non-existant. I understand that the values are provided by https://github.com/Pathoschild/Wikimedia-contrib/blob/master/user-scripts/pathoschild.stewardscript.js#L150-L156 but I'm not sure what do I have to add/remove/modify in order to achieve the goal I suggested.

**Comment by Pathoschild** [comment]
@MarcoAurelioWM I can't really help, since I can't access the page the script changes. Are any of the current stewards familiar with JavaScript?

**Comment by Pathoschild** [comment]
I'm no longer very active on Wikimedia wikis, so I'm not actively developing new features for these scripts. (I'm still maintaining the existing scripts though.) I'll close this as _won't do_, but pull requests are welcome if someone wanted to tackle this.
