### ISSUE TITLE
Scripts don't declare RL module dependencies

### ISSUE THREAD

**Issue by hartman** [Pathoschild/Wikimedia-contrib#89]
Hi, this script is not declaring/enforcing it's dependency on mediawiki.util. This likely causes JS errors for users of this script, as Paine Ellsworth, who has this installed in [global.js](https://meta.wikimedia.org/wiki/User:Paine_Ellsworth/global.js) 

See also report:
https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(technical)#Edit_screen_instability

**Comment by Pathoschild** [comment]
Fixed in c4c70eaf594f99af6c1290a8a8e4020210ccc38e and deployed. You may need to [clear your cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) to see the changes. Let me know whether you still have any issues. :)
