### ISSUE TITLE
[stalktoy] The Wikiversity is missing in the first pie chart

### ISSUE THREAD

**Issue by JackPotte** [Pathoschild/Wikimedia-contrib#90]
Example: https://tools.wmflabs.org/meta/stalktoy/JackPotte
![image](https://cloud.githubusercontent.com/assets/6272739/25577398/f8107a3c-2e65-11e7-9ab9-f4a2bad6394d.png)

**Comment by Pathoschild** [comment]
That's strange, it shows up fine for me:
> ![](https://cloud.githubusercontent.com/assets/230581/25583959/02c4ee44-2e62-11e7-93cc-5615a1791aa5.png)

I also see very different numbers in the chart (e.g. 58.5% Wiktionary instead of the 73.3% in your screenshot). Are there any JavaScript errors when that happens?

**Comment by Pathoschild** [comment]
Closed due to lack of response.
