### ISSUE TITLE
[AJAX sysop] Revert links makes you jump to the top of the page

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#91]
When trying to rollback an edit using the ajax rollback, it always bring me to the top of the page. Any idea why that might be happening?

**Comment by Pathoschild** [comment]
Fixed and deployed. You may need to [clear your cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) to see the changes. :)
