### ISSUE TITLE
Missing databases (recently deleted wikis) broke some tools

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Pathoschild/Wikimedia-contrib#95]
als.wikibooks, als.wikiquote and als.wiktionary, and mo.wikipedia and mo.wiktionary wikis were deleted yesterday, and its replicas were dropped some days ago. However https://tools.wmflabs.org/meta/userpages/Evolution+and+evolvability fails because the tool can't reach alswikibooks_p. Not sure if this is something you can fix on your tool directly or it requires WM Cloud Services input. Thanks.

**Comment by MarcoAurelioWM** [comment]
https://github.com/Pathoschild/Wikimedia-contrib/blob/f94b7aa1e9a3c7b3e5899db33d939098c7335490/tool-labs/userpages/index.php#L59-L64

Don't we need to use the new Toolforge databases here?

**Comment by Pathoschild** [comment]
@MarcoAurelioWM The tools now ignore those wikis. Thanks for reporting it!

That code does use the new Toolforge databases. The tools request the database for a wiki, which is mapped at a lower level to the database shard:
https://github.com/Pathoschild/Wikimedia-contrib/blob/f94b7aa/tool-labs/backend/modules/Wikimedia.php#L43-L52

**Comment by DDGo** [comment]
Old meta_p table on Toolforge replicas caused this issue. [https://phabricator.wikimedia.org/T184433](See Phabricator)
